export const RESGITER_REQUEST = "@authReducer/AUTH_REQUEST";
export const RESGITER_SUCCESS = "@RESGITERReducer/RESGITER_SUCCESS";
export const RESGITER_FAILED = "@RESGITERReducer/RESGITER_FAILED";
export const RESGITER_CLEAR_DATA = "@RESGITERReducer/RESGITER_CLEAR_DATA";
